[book]
authors = ["Chen-Pang He"]
title = "橋牌入門：從規則到二蓋一"
language = "zh-TW"

[output.html]
additional-css = ["style.css"]
site-url = "https://jdh8.github.io/bridge-tutorial/"
git-repository-url = "https://github.com/jdh8/bridge-tutorial"
edit-url-template = "https://github.com/jdh8/bridge-tutorial/edit/main/{path}"

[preprocessor.replace]

[preprocessor.replace.list]
"♠" = "<span class='♠'>♠</span>"
"♥" = "<span class='♥'>♥</span>"
"♦" = "<span class='♦'>♦</span>"
"♣" = "<span class='♣'>♣</span>"

[preprocessor.abbr]

[preprocessor.abbr.list]
BTU = "台大橋藝社"
BWS = "Bridge World Standard 2017"
GF = "game forcing（迫叫成局）"
HCP = "high-card points（大牌點）"
RKCB = "Roman Key-Card Blackwood"
